obj-$(CONFIG_OPLUS_MODULES) += oplus_dns_hook.o oplus_stats_calc.o oplus_qr_scan.o oplus_data_module.o

oplus_data_module-objs := data_main.o \
			comm_netlink/comm_netlink.o \
			comm_netlink/protobuf-c.o \
			proto-src/netlink_msg.pb-c.o \
			dpi/dpi_core.o \
			dpi/log_stream.o\
			dpi/tmgp_sgame.o \
			dpi/heytap_market.o \
			cls_dpi/cls_dpi.o \
			tmgp_sgame/wzry_stats.o
